version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=dynamodb, sqs, sns, lambda, ec2, cloudformation, s3
      - DYNAMODB_OPTIMIZE_DB_BEFORE_STARTUP=1
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=guest
      - AWS_SECRET_ACCESS_KEY=guest
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SECURITY_TOKEN=guest
      - AWS_SESSION_TOKEN=guest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./data/localstack/data:/localstack/data
      - ./script/localstack/dynamodb:/localstack/tables
      - ./script/localstack/dynamodb/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
